using Domain;
using Infrastructure.Entities;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Contexts;

/// <summary>
/// Inspired by Hans :) Thanks
/// </summary>
/// <param name="options"></param>
public class DataContext(DbContextOptions<DataContext> options) : DbContext(options)
{
    /*
        # Navigate to your Infrastructure project directory
        cd Infrastructure

        # Add migration
        dotnet ef migrations add InitialMigration

        # Update database
        dotnet ef database update
     */

    public DbSet<StatusEntity> Status { get; set; }
    public DbSet<RolesEntity> Roles { get; set; }
    public DbSet<UsersEntity> Users { get; set; }
    public DbSet<ProjectsEntity> Projects { get; set; }
    public DbSet<CustomersEntity> Customers { get; set; }
    public DbSet<PaymentTypeEntity> PaymentType { get; set; }
    public DbSet<ServicesEntity> Services { get; set; }

    // Here is where we define our tables
    // Specify Connection String in the app settings.json, if using multiple presentation
    // layers, you can specify the connection string in the appsettings.json of the presentation layer
    // We could activate the lazy loading here as well
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // Using Logs this to log sensitive data for developers
        optionsBuilder.EnableSensitiveDataLogging();
        // We can also enable caching here
        optionsBuilder.EnableServiceProviderCaching();
    }

    /// <summary>
    /// This is needed if we have multiple keys in a table to add the composite key (Two Primary Keys)
    /// Then this is needed to be added to the OnModelCreating. What should I do without Hans? :)
    /// </summary>
    /// <param name="modelBuilder"></param>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        // modelBuilder.Entity<TableName>().HasKey(x => new { x.Key1, x.Key2 });
        // If we want to make a column unique but could also be set in our Entity as well and not just here
        // modelBuilder.Entity<TableName>().HasIndex(x => x.Key1).IsUnique();

        // Composite Key for Customers and a unique constraint for Name and ContactPersonId
        modelBuilder.Entity<CustomersEntity>(entity =>
        {
            // Composite Key for Customers ID
            entity.HasKey(e => new { e.Id });
            // Adding a unique constraint to the Name and ContactPersonId
            entity
                .HasIndex(e => new { e.Name, e.ContactPersonId })
                .IsUnique()
                .HasDatabaseName("IX_Customers_Name_ContactPersonId");
        });

        // Configure the many-to-many relationship between Users and Roles
        // This is a many-to-many relationship between Users and Roles
        // Code and comments generated by AI Phind 100%
        modelBuilder
            // Start with the Users entity
            .Entity<UsersEntity>()
            // Specify that one user can have many roles
            .HasMany(u => u.RolesEntity)
            // Specify that one role can have many users (completing many-to-many relationship)
            .WithMany(r => r.UsersEntity)
            // Configure the join table without creating a concrete entity class
            .UsingEntity<Dictionary<string, object>>(
                // Name of the join table in the database
                "RolesUsers",
                // Configure the Role side of the relationship
                join =>
                    join.HasOne<RolesEntity>() // Each entry in join table connects to one role
                        .WithMany() // A role can be referenced by many join table entries
                        .HasForeignKey("RolesEntityId") // Name of the foreign key column for roles
                        .OnDelete(DeleteBehavior.ClientNoAction), // Prevent cascade deletes from roles
                // Configure the User side of the relationship
                join =>
                    join.HasOne<UsersEntity>() // Each entry in join table connects to one user
                        .WithMany() // A user can be referenced by many join table entries
                        .HasForeignKey("UsersEntityId") // Name of the foreign key column for users
                        .OnDelete(DeleteBehavior.ClientNoAction) // Prevent cascade deletes from users
            );

        // Configure the many-to-many relationship between Projects and Services
        // This is a many-to-many relationship between Projects and Services
        // Code and comments generated by AI Phind 100%
        modelBuilder
            // Start with the Projects entity
            .Entity<ProjectsEntity>()
            // Specify that one project can have many services
            .HasMany(p => p.ServicesEntity)
            // Specify that one service can have many projects (completing many-to-many relationship)
            .WithMany(s => s.ProjectsEntity)
            // Configure the join table without creating a concrete entity class
            .UsingEntity<Dictionary<string, object>>(
                // Name of the join table in the database
                "ProjectServices",
                // Configure the Service side of the relationship
                j =>
                    j.HasOne<ServicesEntity>() // Each entry in join table connects to one service
                        .WithMany() // A service can be referenced by many join table entries
                        .HasForeignKey("ServicesEntityId") // Name of the foreign key column for services
                        .OnDelete(DeleteBehavior.ClientNoAction), // Prevent cascade deletes from services
                // Configure the Project side of the relationship
                j =>
                    j.HasOne<ProjectsEntity>() // Each entry in join table connects to one project
                        .WithMany() // A project can be referenced by many join table entries
                        .HasForeignKey("ProjectsEntityId") // Name of the foreign key column for projects
                        .OnDelete(DeleteBehavior.ClientNoAction) // Prevent cascade deletes from projects
            );

        // Unique constraint for the Firstname and LastName in the Roles table
        //    modelBuilder.Entity<Users>(entity =>
        //    {
        //        entity
        //            .HasIndex(u => new { u.FirstName, u.LastName })
        //            .IsUnique()
        //            .HasDatabaseName("IX_Users_FirstName_LastName");
        //    });

        // Inspired by Robin
        // Setting the Identity column to start at 100 and increment by 1
        modelBuilder
            .Entity<ProjectsEntity>()
            .Property(p => p.Id)
            .UseIdentityColumn(100, 1);

        // Loading the configurations from the DataSeeding folder to seed the database
        // Inspired by Robin and Partially created by AI Phind
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(DataContext).Assembly);
    }
}
